<?php

/**
 * TDProject_Project
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

?>
<script type="text/javascript">

$(document).ready(function() {
    $("#accordion").accordion();
});

</script>
<fieldset class="ui-widget ui-widget-content ui-corner-all">
    <legend>Statistics</legend>
    <p>Dieser Bereich wird künftig einen Überblick über die Projekt- und
    Benutzer Statistiken geben.</p>
    <p>Zu diesem Bereich haben nur Benutzer mit der Rolle Administratoren Zugriff</p>
    <div id="accordion">
	    <h3>
	    	<a href="#">Benutzer</a>
	    </h3>
	    <div>
	    	Klicken Sie hier um einen Überblick über die
	    	<a onclick="window.location='';" href="#">Benutzer-Performance</a> zu erhalten.
		</div>
	    <h3>
	    	<a href="#">Projekte</a>
	    </h3>
	    <div>
	    	Klicken Sie hier um einen Überblick über die
	    	<a onclick="window.location='';" href="#">Projekt-Performance</a> zu erhalten.
		</div>
	</div>
</fieldset>